variables:
  PROJECT_NAME: glitchtip
  COMPOSE: docker-compose -p glitchtip
  IMAGE_NAME: registry.gitlab.com/glitchtip/glitchtip-backend
  CONTAINER_TEST_IMAGE: registry.gitlab.com/glitchtip/glitchtip-backend:$CI_BUILD_REF_NAME

test:
  image: python:3.8
  services:
    - name: postgres:10-alpine
      alias: db
  script:
    - pip install -r requirements.txt
    - ./manage.py test

build:
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker pull $IMAGE_NAME:latest || true
    - $COMPOSE build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker tag ${PROJECT_NAME}_web ${IMAGE_NAME}:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_TEST_IMAGE

