variables:
  PROJECT_NAME: glitchtip
  COMPOSE: docker-compose -p glitchtip
  IMAGE_NAME: registry.gitlab.com/glitchtip/glitchtip-backend
  CONTAINER_TEST_IMAGE: registry.gitlab.com/glitchtip/glitchtip-backend:$CI_BUILD_REF_NAME
  POETRY_VERSION: 1.0.5
  POETRY_VIRTUALENVS_CREATE: 'false'
  PIP_DISABLE_PIP_VERSION_CHECK: "on"
  POSTGRES_HOST_AUTH_METHOD: "trust"

test:
  image: python:3.8-slim
  variables:
    SECRET_KEY: testing
  services:
    - postgres
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
  script:
    - apt-get update && apt-get install -y gcc
    - pip install "poetry==$POETRY_VERSION"
    - poetry install --no-interaction --no-ansi
    - ./manage.py test

build:
  image: docker:stable
  services:
    - docker:19.03.5-dind
  script:
    - apk add --no-cache docker-compose
    - docker pull $IMAGE_NAME:latest || true
    - $COMPOSE build --build-arg IS_CI="True"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker tag ${PROJECT_NAME}_web ${IMAGE_NAME}:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_TEST_IMAGE

