version: "3.4"
services:
  locust:
    build: .
    command: locust --host http://web:8000
    volumes:
      - .:/code
    ports:
      - "8089:8089"
    environment:
      DJANGO_SETTINGS_MODULE: glitchtip.settings
      SECRET_KEY: nope
