version: '3.2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
