[tool.poetry]
name = "glitchtip-backend"
version = "0.1.0"
description = "Django backend that powers GlitchTip, an open source reimplementation of Sentry"
authors = ["David Burke"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.1"
djangorestframework = "~3.11.2"
django-allauth = "^0.42.0"
django-cors-headers = "^3.2.0"
django-debug-toolbar = "~3.1.1"
django-environ = "^0.4.5"
django-extensions = "^3.0.2"
django-organizations = "^1.1.2"
django-storages = "^1.8"
drf-nested-routers = "^0.91"
psycopg2-binary = "^2.8.4"
uWSGI = "^2.0.18"
whitenoise = "^5.0.1"
boto3 = "^1.10.44"
sentry-sdk = "^0.18.0"
django-filter = "^2.2.0"
celery = {extras = ["redis"], version = "~4.4.6"}
django-celery-results = "^1.2.0"
django-redis-cache = "2.1.1"
redis = "^3.3.11"
jsonschema = "^3.2.0"
simplejson = "^3.17.0"
django-csp = "^3.6"
dj-stripe = "^2.2.3"
django-anymail = "~8.0.0"
drf-yasg = "^1.17.1"
dj-rest-auth = "^1.0.5"
user-agents = "^2.1"
django-bitfield = "^2.0.1"
django-ipware = "^3.0.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
ipdb = "^0.13.2"
pylint = "^2.4.4"
pylint-django = "^2.0.13"
locust = "^1.1.1"
freezegun = "~1.0.0"
rope = "^0.17.0"
model_bakery = "^1.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
